## Creating a logistic regression to predict absenteeism

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data_preprocessed = pd.read_csv(r"F:\Udemy casse syudy\Absenteeism_data_preprocessed.csv")

In [3]:
data_preprocessed.head(10)

,reason_1,reason_2,reason_3,reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value,Day of the Week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,0,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,0,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,0,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,0,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,0,2,1,2,7,3
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,0,0,0,2,7,4
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,0,1,4,8,7,4
7,0,0,0,1,2015-07-24,260,50,36,239.554,23,0,4,0,4,7,4
8,0,0,1,0,2015-07-06,155,12,34,239.554,25,0,2,0,40,7,0
9,0,0,0,1,2015-07-13,235,11,37,239.554,29,1,1,1,8,7,0

## Create the targets

In [4]:
# get median 
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [7]:
data_preprocessed['Exessive Absenteeism'] = targets

In [8]:
data_preprocessed.head(7)

,reason_1,reason_2,reason_3,reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value,Day of the Week,Exessive Absenteeism
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,0,2,1,4,7,1,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,0,1,0,0,7,1,0
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,0,0,0,2,7,2,0
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,0,2,0,4,7,3,1
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,0,2,1,2,7,3,0
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,0,0,0,2,7,4,0
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,0,1,4,8,7,4,1

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

In [11]:
# do two variables have the same memory 
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets = data_with_targets.drop(['Date'], axis = 1)

In [13]:
data_with_targets.head(3)

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week,Exessive Absenteeism
0,0,0,0,1,289,36,33,239.554,30,0,2,1,7,1,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,7,1,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,7,2,0

In [14]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

## standarize the data

In [15]:
from sklearn.preprocessing import StandardScaler

absenteesim_scaler = StandardScaler()

E:\Anaconada\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        # Initializing StandardScaler with the passed arguments
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns 
        self.mean_ = None 
        self.var_ = None
        
    def fit(self, X, y=None):
        # Fitting the scaler to the selected columns
        self.scaler.fit(X[self.columns], y)
        # Storing the mean and variance
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self 
    
    def transform(self, X, y=None):
        # Transforming the selected columns using the fitted scaler
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        # Keeping the columns that were not scaled
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        # Returning the DataFrame with original column order
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [18]:
#columns_to_scale = ['Transportation Expense', 'Age', 'Body Mass Index',
                   # 'Children', 'Pets','Month Value']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

,reason_1,reason_2,reason_3,reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Month Value,Day of the Week
0,-0.577350,-0.092981,-0.314485,0.821365,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487,0.182726,-0.683704
1,-0.577350,-0.092981,-0.314485,-1.217485,-1.574681,-1.141882,2.130803,-0.806331,1.002633,0,-0.019280,-0.589690,0.182726,-0.683704
2,-0.577350,-0.092981,-0.314485,0.821365,-0.654143,1.426749,0.248310,-0.806331,1.002633,0,-0.919030,-0.589690,0.182726,-0.007725
3,1.732051,-0.092981,-0.314485,-1.217485,0.854936,-1.682647,0.405184,-0.806331,-0.643782,0,0.880469,-0.589690,0.182726,0.668253
4,-0.577350,-0.092981,-0.314485,0.821365,1.005844,0.412816,-0.536062,-0.806331,0.767431,0,0.880469,0.268487,0.182726,0.668253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1.732051,-0.092981,-0.314485,-1.217485,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,1,0.880469,-0.589690,-0.388293,-0.007725
696,1.732051,-0.092981,-0.314485,-1.217485,0.040034,-0.263140,-1.320435,-0.853789,-0.643782,0,-0.019280,1.126663,-0.388293,-0.007725
697,1.732051,-0.092981,-0.314485,-1.217485,1.624567,-0.939096,-1.320435,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,0.668253
698,-0.577350,-0.092981,-0.314485,0.821365,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,1,-0.919030,-0.589690,-0.388293,0.668253
699,-0.577350,-0.092981,-0.314485,0.821365,1.036026,0.074838,0.562059,-0.853789,-0.408580,0,-0.019280,0.268487,-0.388293,0.668253

## Split the data into train and test and shuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [26]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)

In [27]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)

## Logistic regression with sklearn

In [28]:
from sklearn.linear_model import LogisticRegression 
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
reg.score(x_train,y_train)

0.7839285714285714

In [32]:
reg.intercept_

array([-0.1669092])

In [33]:
reg.coef_

array([[ 2.07452606,  0.33355827,  1.55923   ,  1.32893272,  0.70486037,
        -0.03682454, -0.19993103, -0.00319661,  0.3227044 , -0.3323036 ,
         0.38398576, -0.33216428,  0.18893894, -0.07135387]])

In [34]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [35]:
feature_name = unscaled_inputs.columns.values

In [36]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['coefficient'] = np.transpose(reg.coef_)

summary_table

               Feature name  coefficient
0                  reason_1     2.074526
1                  reason_2     0.333558
2                  reason_3     1.559230
3                  reason_4     1.328933
4    Transportation Expense     0.704860
5          Distance to Work    -0.036825
6                       Age    -0.199931
7   Daily Work Load Average    -0.003197
8           Body Mass Index     0.322704
9                 Education    -0.332304
10                 Children     0.383986
11                     Pets    -0.332164
12              Month Value     0.188939
13          Day of the Week    -0.071354

In [37]:
summary_table.index = summary_table.index + 1 
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

               Feature name  coefficient
0                 Intercept    -0.166909
1                  reason_1     2.074526
2                  reason_2     0.333558
3                  reason_3     1.559230
4                  reason_4     1.328933
5    Transportation Expense     0.704860
6          Distance to Work    -0.036825
7                       Age    -0.199931
8   Daily Work Load Average    -0.003197
9           Body Mass Index     0.322704
10                Education    -0.332304
11                 Children     0.383986
12                     Pets    -0.332164
13              Month Value     0.188939
14          Day of the Week    -0.071354

## Interpreting the coafficients

In [38]:
summary_table['Odds_ratio'] = np.exp(summary_table.coefficient)

In [39]:
summary_table

               Feature name  coefficient  Odds_ratio
0                 Intercept    -0.166909    0.846276
1                  reason_1     2.074526    7.960773
2                  reason_2     0.333558    1.395926
3                  reason_3     1.559230    4.755158
4                  reason_4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
6          Distance to Work    -0.036825    0.963845
7                       Age    -0.199931    0.818787
8   Daily Work Load Average    -0.003197    0.996808
9           Body Mass Index     0.322704    1.380857
10                Education    -0.332304    0.717270
11                 Children     0.383986    1.468125
12                     Pets    -0.332164    0.717369
13              Month Value     0.188939    1.207967
14          Day of the Week    -0.071354    0.931132

In [40]:
summary_table.sort_values('Odds_ratio', ascending=False)

               Feature name  coefficient  Odds_ratio
1                  reason_1     2.074526    7.960773
3                  reason_3     1.559230    4.755158
4                  reason_4     1.328933    3.777010
5    Transportation Expense     0.704860    2.023564
11                 Children     0.383986    1.468125
2                  reason_2     0.333558    1.395926
9           Body Mass Index     0.322704    1.380857
13              Month Value     0.188939    1.207967
8   Daily Work Load Average    -0.003197    0.996808
6          Distance to Work    -0.036825    0.963845
14          Day of the Week    -0.071354    0.931132
0                 Intercept    -0.166909    0.846276
7                       Age    -0.199931    0.818787
12                     Pets    -0.332164    0.717369
10                Education    -0.332304    0.717270

## testing the model

In [41]:
reg.score(x_test,y_test)

0.7357142857142858

In [42]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73818406, 0.26181594],
       [0.58978443, 0.41021557],
       [0.36634007, 0.63365993],
       [0.81220479, 0.18779521],
       [0.06146199, 0.93853801],
       [0.30790074, 0.69209926],
       [0.29670107, 0.70329893],
       [0.08157059, 0.91842941],
       [0.80560765, 0.19439235],
       [0.76015779, 0.23984221],
       [0.46268566, 0.53731434],
       [0.15612304, 0.84387696],
       [0.04645643, 0.95354357],
       [0.72518161, 0.27481839],
       [0.23401317, 0.76598683],
       [0.54800338, 0.45199662],
       [0.52970199, 0.47029801],
       [0.55485413, 0.44514587],
       [0.38448275, 0.61551725],
       [0.0254313 , 0.9745687 ],
       [0.69717166, 0.30282834],
       [0.80473679, 0.19526321],
       [0.37908634, 0.62091366],
       [0.40204277, 0.59795723],
       [0.18482564, 0.81517436],
       [0.76088002, 0.23911998],
       [0.47365773, 0.52634227],
       [0.88833741, 0.11166259],
       [0.13622021, 0.86377979],
       [0.79704602, 0.20295398],
       [0.61724287, 0.38275713],
       [0.29707108, 0.70292892],
       [0.2979493 , 0.7020507 ],
       [0.43613016, 0.56386984],
       [0.80473679, 0.19526321],
       [0.45773286, 0.54226714],
       [0.79644632, 0.20355368],
       [0.18134989, 0.81865011],
       [0.55494775, 0.44505225],
       [0.38899181, 0.61100819],
       [0.79063728, 0.20936272],
       [0.59385099, 0.40614901],
       [0.78743744, 0.21256256],
       [0.9013724 , 0.0986276 ],
       [0.15712656, 0.84287344],
       [0.33753703, 0.66246297],
       [0.28571024, 0.71428976],
       [0.72935276, 0.27064724],
       [0.80060529, 0.19939471],
       [0.82914626, 0.17085374],
       [0.42248545, 0.57751455],
       [0.91554957, 0.08445043],
       [0.32037645, 0.67962355],
       [0.71567443, 0.28432557],
       [0.12836493, 0.87163507],
       [0.51535458, 0.48464542],
       [0.06810541, 0.93189459],
       [0.75508981, 0.24491019],
       [0.91796005, 0.08203995],
       [0.9173522 , 0.0826478 ],
       [0.26896741, 0.73103259],
       [0.33083452, 0.66916548],
       [0.68919787, 0.31080213],
       [0.14156802, 0.85843198],
       [0.8165459 , 0.1834541 ],
       [0.7399696 , 0.2600304 ],
       [0.98695962, 0.01304038],
       [0.78088426, 0.21911574],
       [0.19072885, 0.80927115],
       [0.6800822 , 0.3199178 ],
       [0.79694263, 0.20305737],
       [0.92936763, 0.07063237],
       [0.06667849, 0.93332151],
       [0.53635656, 0.46364344],
       [0.34478172, 0.65521828],
       [0.79704602, 0.20295398],
       [0.14950984, 0.85049016],
       [0.27576715, 0.72423285],
       [0.21204315, 0.78795685],
       [0.31111111, 0.68888889],
       [0.76000589, 0.23999411],
       [0.98787092, 0.01212908],
       [0.78137722, 0.21862278],
       [0.24029097, 0.75970903],
       [0.56680723, 0.43319277],
       [0.89952202, 0.10047798],
       [0.28335644, 0.71664356],
       [0.41339043, 0.58660957],
       [0.95111004, 0.04888996],
       [0.30724079, 0.69275921],
       [0.86255514, 0.13744486],
       [0.87888123, 0.12111877],
       [0.78840954, 0.21159046],
       [0.72130904, 0.27869096],
       [0.77730196, 0.22269804],
       [0.10843952, 0.89156048],
       [0.72711985, 0.27288015],
       [0.1916403 , 0.8083597 ],
       [0.7736461 , 0.2263539 ],
       [0.79692036, 0.20307964],
       [0.33149792, 0.66850208],
       [0.28709848, 0.71290152],
       [0.27146048, 0.72853952],
       [0.27360405, 0.72639595],
       [0.51380519, 0.48619481],
       [0.46217859, 0.53782141],
       [0.7484223 , 0.2515777 ],
       [0.12324215, 0.87675785],
       [0.19859527, 0.80140473],
       [0.85757816, 0.14242184],
       [0.98909622, 0.01090378],
       [0.07564174, 0.92435826],
       [0.26622198, 0.73377802],
       [0.64395966, 0.35604034],
       [0.42402604, 0.57597396],
       [0.39641569, 0.60358431],
       [0.13185636, 0.86814364],
       [0.1672064 , 0.8327936 ],
       [0.46701566, 0.53298434],
       [0.69520246, 0.30479754],
       [0.76734496, 0.23265504],
       [0.85387579, 0.14612421],
       [0.12931126, 0.87068874],
       [0.55853225, 0.44146775],
       [0.79704602, 0.20295398],
       [0.61873823, 0.38126177],
       [0.81358454, 0.18641546],
       [0.89372731, 0.10627269],
       [0.23355821, 0.76644179],
       [0.68624204, 0.31375796],
       [0.33234191, 0.66765809],
       [0.806003  , 0.193997  ],
       [0.68721346, 0.31278654],
       [0.65223933, 0.34776067],
       [0.71488425, 0.28511575],
       [0.45926982, 0.54073018],
       [0.54027611, 0.45972389],
       [0.69893216, 0.30106784],
       [0.74730947, 0.25269053],
       [0.53595344, 0.46404656]])

In [43]:
predicted_proba.shape

(140, 2)

## Save model

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [46]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)